package com.sample
 
import com.sample.MarklinTrain;
import java.util.Scanner;

rule "Acoplador de metal esta dobrado?"
    salience 100
    when
        $t:MarklinTrain(getComponente(0)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("O acoplador de metal da locomotiva encontra-se dobrado ?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("sim"))
        	$t.setComponente(0, 1);
		else
			$t.setComponente(0, 0);
			
		update($t);
end

rule "Existe curto circuito entre corpo e fio?"
    salience 99
    when
        $t:MarklinTrain(getComponente(1)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("Existe curto circuito entre corpo e fio ?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("sim"))
        	$t.setComponente(1, 1);
		else
			$t.setComponente(1, 0);
			
		update($t);
end

rule "Existe curto circuito entre corpo e ponto de soldadura?"
    salience 98
    when
        $t:MarklinTrain(getComponente(2)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("Existe curto circuito entre corpo e ponto de soldadura?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("sim"))
        	$t.setComponente(2, 1);
		else
			$t.setComponente(2, 0);
			
		update($t);
end

rule "Algum fio de luz está a causar curto-circuito?"
    salience 97
    when
        $t:MarklinTrain(getComponente(3)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("Algum fio de luz está a causar curto-circuito?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("sim"))
        	$t.setComponente(3, 1);
		else
			$t.setComponente(3, 0);
			
		update($t);
end

rule "A alavanca seletora está configurada?"
    salience 96
    when
        $t:MarklinTrain(getComponente(4)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("A alavanca seletora está configurada?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("nao"))
        	$t.setComponente(4, 1);
		else
			$t.setComponente(4, 0);
			
		update($t);
end

rule "A parte superior da alavanca esta bem colocada ?"
    salience 94
    when
        $t:MarklinTrain(getComponente(5)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("A parte superior da alavanca esta bem colocada ?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("nao"))
        	$t.setComponente(5, 1);
		else
			$t.setComponente(5, 0);
			
		update($t);
end

rule "Existe mau contacto entre placa de comutação na placa de contacto ?"
    salience 93
    when
        $t:MarklinTrain(getComponente(6)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("Existe mau contacto entre placa de comutação na placa de contacto ?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("sim"))
        	$t.setComponente(6, 1);
		else
			$t.setComponente(6, 0);
			
		update($t);
end

rule "Existe mau contacto entre o patim da locomotiva e o carril ?"
    salience 92
    when
        $t:MarklinTrain(getComponente(7)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("Existe mau contacto entre o patim da locomotiva e o carril ?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("sim"))
        	$t.setComponente(7, 1);
		else
			$t.setComponente(7, 0);
			
		update($t);
end

rule "O fio da placa do contacto está solto?"
    salience 93
    when
        $t:MarklinTrain(getComponente(8)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("O fio da placa do contacto está solto?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("sim"))
        	$t.setComponente(8, 1);
		else
			$t.setComponente(8, 0);
			
		update($t);
end

rule "Existe mau contacto entre a placa de contacto e o ponto de soldadura ?"
    salience 92
    when
        $t:MarklinTrain(getComponente(9)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("Existe mau contacto entre a placa de contacto e o ponto de soldadura ?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("sim"))
        	$t.setComponente(9, 1);
		else
			$t.setComponente(9, 0);
			
		update($t);
end

rule "A válvula está a funcionar corretamente?"
    salience 91
    when
        $t:MarklinTrain(getComponente(10)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("A válvula está a funcionar corretamente?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("nao"))
        	$t.setComponente(10, 1);
		else
			$t.setComponente(10, 0);
			
		update($t);
end

rule "As rodas dianteiras  giram com força manual ? "
    salience 90
    when
        $t:MarklinTrain(getComponente(11)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("As rodas dianteiras  giram com força manual ? ");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("nao"))
        	$t.setComponente(11, 1);
		else
			$t.setComponente(11, 0);
			
		update($t);
end

rule "As escovas estão em falta/demasiado curtas?"
    salience 89
    when
        $t:MarklinTrain(getComponente(12)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("As escovas estão em falta/demasiado curtas?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("sim"))
        	$t.setComponente(12, 1);
		else
			$t.setComponente(12, 0);
			
		update($t);
end

rule "As ligações entre o íman e a unidade reversa estão quebradas?"
    salience 88
    when
        $t:MarklinTrain(getComponente(13==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("As ligações entre o íman e a unidade reversa estão quebradas?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("sim"))
        	$t.setComponente(13, 1);
		else
			$t.setComponente(13, 0);
			
		update($t);
end

rule "A unidade reversa arranca no momento em que o transformador é virada para cima?"
    salience 87
    when
        $t:MarklinTrain(getComponente(14)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("A unidade reversa arranca no momento em que o transformador é virada para cima?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("nao"))
        	$t.setComponente(14, 1);
		else
			$t.setComponente(14, 0);
			
		update($t);
end

rule "O interruptor tem contacto com a placa de contacto?"
    salience 86
    when
        $t:MarklinTrain(getComponente(15)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("O interruptor tem contacto com a placa de contacto?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("nao"))
        	$t.setComponente(15, 1);
		else
			$t.setComponente(15, 0);
			
		update($t);
end

rule "A mola do interruptor tem pouca tensão?"
    salience 85
    when
        $t:MarklinTrain(getComponente(16)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("A mola do interruptor tem pouca tensão?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("sim"))
        	$t.setComponente(16, 1);
		else
			$t.setComponente(16, 0);
			
		update($t);
end

rule "O indutor faz barulho quando o controlador de velocidade está ligado?"
    salience 84
    when
        $t:MarklinTrain(getComponente(17)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("O indutor faz barulho quando o controlador de velocidade está ligado?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("sim"))
        	$t.setComponente(17, 1);
		else
			$t.setComponente(17, 0);
			
		update($t);
end

rule "O indutor não faz barulho quando o controlador de velocidade está ligado?"
    salience 83
    when
        $t:MarklinTrain(getComponente(18)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("O indutor não faz barulho quando o controlador de velocidade está ligado?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("sim"))
        	$t.setComponente(18, 1);
		else
			$t.setComponente(18, 0);
			
		update($t);
end

rule "Há corrente na catenária?"
    salience 82
    when
        $t:MarklinTrain(getComponente(19)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("Há corrente na catenária?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("nao"))
        	$t.setComponente(19, 1);
		else
			$t.setComponente(19, 0);
			
		update($t);
end

rule "A alavanca seletora está configurada para operar a catenária? "
    salience 81
    when
        $t:MarklinTrain(getComponente(20)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("A alavanca seletora está configurada para operar a catenária?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("nao"))
        	$t.setComponente(20, 1);
		else
			$t.setComponente(20, 0);
			
		update($t);
end

rule "A alavanca seletora está a funcionar corretamente ?"
    salience 80
    when
        $t:MarklinTrain(getComponente(21)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("A alavanca seletora está a funcionar corretamente ?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("nao"))
        	$t.setComponente(21, 1);
		else
			$t.setComponente(21, 0);
			
		update($t);
end

rule "Há contacto entre a mola da alavanca seletora e o pantógrafo? "
    salience 79
    when
        $t:MarklinTrain(getComponente(22)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("Há contacto entre a mola da alavanca seletora e o pantógrafo?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("nao"))
        	$t.setComponente(22, 1);
		else
			$t.setComponente(22, 0);
			
		update($t);
end

rule "As molas do pantógrafo estão bem conectadas ?"
    salience 78
    when
        $t:MarklinTrain(getComponente(23)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("As molas do pantógrafo estão bem conectadas ?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("nao"))
        	$t.setComponente(23, 1);
		else
			$t.setComponente(23, 0);
			
		update($t);
end

rule "O pantógrafo está dobrado?"
    salience 77
    when
        $t:MarklinTrain(getComponente(24)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("O pantógrafo está dobrado?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("sim"))
        	$t.setComponente(24, 1);
		else
			$t.setComponente(24, 0);
			
		update($t);
end

rule "As pontas de soldadura entre o indutor e a unidade reversa ou entre o indutor e a placa de escova estão bem?? "
    salience 76
    when
        $t:MarklinTrain(getComponente(25)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("As pontas de soldadura entre o indutor e a unidade reversa ou entre o indutor e a placa de escova estão bem?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("nao"))
        	$t.setComponente(25, 1);
		else
			$t.setComponente(25, 0);
			
		update($t);
end

rule "O interruptor entre a unidade reversa tem contacto com a placa de contacto para todas as definições?"
    salience 75
    when
        $t:MarklinTrain(getComponente(26)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("O interruptor entre a unidade reversa tem contacto com a placa de contacto para todas as definições?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("nao"))
        	$t.setComponente(26, 1);
		else
			$t.setComponente(26, 0);
			
		update($t);
end

rule "O corredor da unidade reversa está conectado?"
    salience 74
    when
        $t:MarklinTrain(getComponente(27)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("O corredor da unidade reversa está conectado?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("nao"))
        	$t.setComponente(27, 1);
		else
			$t.setComponente(27, 0);
			
		update($t);
end

rule "O pin do corredor que empurra está dobrado?"
    salience 73
    when
        $t:MarklinTrain(getComponente(28)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("O pin do corredor que empurra está dobrado?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("sim"))
        	$t.setComponente(28, 1);
		else
			$t.setComponente(28, 0);
			
		update($t);
end

rule "O gancho para a mola do corredor está dobrado?"
    salience 72
    when
        $t:MarklinTrain(getComponente(29)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("O gancho para a mola do corredor está dobrado?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("sim"))
        	$t.setComponente(29, 1);
		else
			$t.setComponente(29, 0);
			
		update($t);
end

rule "Ao colocar o corpo na frame, há algum fio contra o interruptor?"
    salience 71
    when
        $t:MarklinTrain(getComponente(30)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("Ao colocar o corpo na frame, há algum fio contra o interruptor?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("sim"))
        	$t.setComponente(30, 1);
		else
			$t.setComponente(30, 0);
			
		update($t);
end

rule "O interruptor tem contacto  com a placa de contacto?"
    salience 70
    when
        $t:MarklinTrain(getComponente(31)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("O interruptor tem contacto  com a placa de contacto ?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("nao"))
        	$t.setComponente(31, 1);
		else
			$t.setComponente(31, 0);
			
		update($t);
end

rule "A unidade reversa tem interruptores e pontos de contacto?"
    salience 69
    when
        $t:MarklinTrain(getComponente(32)==-1); 
    then
        Scanner input = new Scanner(System.in);
		System.out.print("A unidade reversa tem interruptores e pontos de contacto?");
		String m = input.nextLine();
        
        if(m.equalsIgnoreCase("sim"))
        	$t.setComponente(32, 1);
		else
			$t.setComponente(32, 0);
			
		update($t);
end